import 'spend_source.dart';
import 'package:uuid/uuid.dart';

//single instance of user spending (either when a new inventoryItem is added or a meal is logged)
//abstract class so only concrete classes: InventoryPurchaseSpend and MealOutSpend implemented
abstract class SpendLogEntry {
  SpendLogEntry({required this.userId, required double amountSpent, required this.entryDate})
      : _amountSpent = amountSpent,
        entryId = const Uuid().v4(); //unique entry id from uuid package for every entry

  //final variables - never assigned again for any SpendLogEntry
  final String entryId;
  final String userId;
  final DateTime entryDate;
  //mutable - amount needs to be updated
  double _amountSpent;

  //a getter exposes private _amountSpent so callers never change value
  double get amountSpent => _amountSpent;

  //Abstract getters, every concrete subclass must implement these
  SpendSource get source;
  String get description;

  //A user can update the amount if they entered it incorrectly, throw an error if negative
  void updateAmount(double newAmount) {
    if (newAmount < 0) throw ArgumentError('amountSpent cannot be negative');
    _amountSpent = newAmount;
  }
}

//SpendLogEntry generated when InventoryItem has a new item added
class InventoryPurchaseSpend extends SpendLogEntry {
  InventoryPurchaseSpend({
    required super.userId, //passed to SpendLogEntry
    required double amountSpent,
    required super.entryDate,
    required this.itemName,
  }) : super(amountSpent: amountSpent);

  final String itemName;

  @override
  SpendSource get source => SpendSource.inventoryItem;
  @override
  String get description => itemName; //only InventoryPurchaseSpend
}

//SpendEntryLog generated by MealLog
class MealOutSpend extends SpendLogEntry {
  MealOutSpend({
    required super.userId,
    required double amountSpent,
    required super.entryDate,
    required this.mealName,
  }) : super(amountSpent: amountSpent);

  final String mealName;

  @override
  SpendSource get source => SpendSource.mealOut;
  @override
  String get description => mealName;
}